### ISSUE TITLE
Error while buiding install target

### ISSUE THREAD

**Issue by EDSONCV** [regwhitton/video-capture-inventory#4]
I am trying to build and I'm getting the following error:

 Failed to execute goal on project video-capture-inventory: Could not resolve dependencies for project com.github.regwhitton:video-capture-inventory:jar:0.1.1: Failed to collect dependencies at cz.adamh.utils:native-utils:jar:1.0  Failed to read artifact descriptor for cz.adamh.utils:native-utils:jar:1.0: The following artifacts could not be resolved: cz.adamh.utils:native-utils:pom:1.0 (absent): Could not transfer artifact cz.adamh.utils:native-utils:pom:1.0 from/to github (https://maven.pkg.github.com/regwhitton/native-utils): status code: 401, reason phrase: Unauthorized (401)

**Comment by regwhitton** [comment]
It looks like you don't have access to the github Maven repo.

Check you have followed the instructions for creating a personal access token and putting it into your Maven settings.xml.  It's been a while since I've used this, so perhaps something has changed.

Alternatively, download the jar directly from [native-utils releases](https://github.com/regwhitton/native-utils/packages/144823) and use [maven install-file](https://maven.apache.org/plugins/maven-install-plugin/install-file-mojo.html) to put it into your local repo.

Or perhaps clone [native-utils repo](https://github.com/regwhitton/native-utils) and use "maven install" to build and install the result in your local repo.

**Comment by regwhitton** [comment]
Assume this must be resolved.
